export const GET_PERSON_DETAILS_REQUEST = "GET_PERSON_DETAILS_REQUEST";
export const GET_PERSON_DETAILS_REQUEST_SUCCESS =
  "GET_PERSON_DETAILS_REQUEST_SUCCESS";
export const GET_PERSON_DETAILS_REQUEST_FAILURE =
  "GET_PERSON_DETAILS_REQUEST_FAILURE";

export const GET_PERSON_HOMEWORLD_SUCCESS = "GET_PERSON_HOMEWORLD_SUCCESS";
export const GET_PERSON_HOMEWORLD_FAILURE = "GET_PERSON_HOMEWORLD_FAILURE";
