export const GET_PLANETS_REQUEST = "GET_PLANETS_REQUEST";
export const GET_PLANETS_REQUEST_SUCCESS = "GET_PLANETS_REQUEST_SUCCESS";
export const GET_PLANETS_REQUEST_FAILURE = "GET_PLANETS_REQUEST_FAILURE";
