export const GET_STARSHIPS_REQUEST = "GET_STARSHIPS_REQUEST";
export const GET_STARSHIPS_SUCCESS = "GET_STARSHIPS_SUCCESS";
export const GET_STARSHIPS_FAILURE = "GET_STARSHIPS_FAILURE";

export const GET_STARSHIP_DETAILS_REQUEST = "GET_STARSHIP_DETAILS_REQUEST";
export const GET_STARSHIP_DETAILS_SUCCESS = "GET_STARSHIP_DETAILS_SUCCESS";
export const GET_STARSHIP_DETAILS_FAILURE = "GET_STARSHIP_DETAILS_FAILURE";
